# fly.toml app configuration file generated for part03-thephonebook on 2024-03-04T09:15:29+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'part03-thephonebook'
primary_region = 'ams'

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
